services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-20971520}
    ports:
      - "0.0.0.0:5000:5000" # 將容器內的 5000 映射到主機的 5000
